#!/bin/sh

# This works for anyone having a ~/.bin/ in their path, but is mostly made to
# suit my environment. For now, you should install this manually instead.

cp tunneltelnet ~/.bin/tunneltelnet
cp tstee ~/.bin/tstee
cp tunneltelnet.conf ~/.tunneltelnet
cp example.proxychains.conf ~/.proxychains.conf
mkdir ~/.tunneltelnet_logs
