#!/usr/bin/env python

import sys
import datetime

outputfile = sys.argv[1]
of = open(outputfile, "w")

while True:
	input_data = sys.stdin.read(1)
	if input_data:
		if input_data == '\n':
			timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S|')
			of.write(input_data + timestamp)
		else:
			of.write(input_data)
		sys.stdout.write(input_data)
		sys.stdout.flush()
	else:
		break

of.close()
