#!/usr/bin/env python

import sys
import datetime


def timestamp():
    return datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S|')

if len(sys.argv) is not 2:
    print 'Usage:', sys.argv[0], '<output file>'
    sys.exit(1)

outputfile = sys.argv[1]
try:
    of = open(outputfile, "w")
except:
    print 'Error: Could not open file!'
    sys.exit(1)

of.write(timestamp())
while True:
    input_data = sys.stdin.read(1)
    if input_data:
        if input_data == '\n':
            of.write(input_data)
            of.write(timestamp())
        else:
            of.write(input_data)

        sys.stdout.write(input_data)
        sys.stdout.flush()
    else:
        break

of.close()
